// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCmoBJJzqjCmfXukcHn-XJa6kLhSFfW08',
    appId: '1:374281219673:web:16b6704c99760468a24b48',
    messagingSenderId: '374281219673',
    projectId: 'cnb-inclubbator',
    authDomain: 'cnb-inclubbator.firebaseapp.com',
    storageBucket: 'cnb-inclubbator.appspot.com',
    measurementId: 'G-2540XH6XTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4NQl7OKBRe4VU637O8Rzs8162eoM7hTQ',
    appId: '1:374281219673:android:54cc0fe805f98be3a24b48',
    messagingSenderId: '374281219673',
    projectId: 'cnb-inclubbator',
    storageBucket: 'cnb-inclubbator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpal-0I_2DlAE-n8OkyxSLT05B7XdyZ74',
    appId: '1:374281219673:ios:0d61bc6025fbddb5a24b48',
    messagingSenderId: '374281219673',
    projectId: 'cnb-inclubbator',
    storageBucket: 'cnb-inclubbator.appspot.com',
    androidClientId: '374281219673-0fhp50ucata0qb2h53ml6siohrsvim37.apps.googleusercontent.com',
    iosClientId: '374281219673-59eoo2f8je105fdk9qurhshqrfk2iu6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.wage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpal-0I_2DlAE-n8OkyxSLT05B7XdyZ74',
    appId: '1:374281219673:ios:0d61bc6025fbddb5a24b48',
    messagingSenderId: '374281219673',
    projectId: 'cnb-inclubbator',
    storageBucket: 'cnb-inclubbator.appspot.com',
    androidClientId: '374281219673-0fhp50ucata0qb2h53ml6siohrsvim37.apps.googleusercontent.com',
    iosClientId: '374281219673-59eoo2f8je105fdk9qurhshqrfk2iu6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.wage',
  );
}
